services:
  - type: web
    name: turuntai-api-prod
    runtime: docker
    region: oregon
    branch: main
    rootDir: server
    dockerfilePath: ./Dockerfile
    autoDeploy: false
    envVars:
      - key: NODE_ENV
        value: production
      - key: FRONTEND_URL
        sync: false

  - type: web
    name: turuntai-api-staging
    runtime: docker
    region: oregon
    branch: dev
    rootDir: server
    dockerfilePath: ./Dockerfile
    autoDeploy: false
    envVars:
      - key: NODE_ENV
        value: staging
      - key: FRONTEND_URL
        sync: false
